# Site settings
name: Osobná webstránka - Stanislav Vnenčák
email: svnencak@gmail.com
tel: +421 917 523 738
author: STANISLAV VNENČÁK
author_desc: FIIT STU - študent
profile_image: /images/profile_image.jpg

keywords: stanislav, vnencak, blog, portfolio
description: Moja osobná webová stránka.

# github_url: "https://speedo-sp7.github.io/"

# Build settings
markdown: kramdown
kramdown:
input: GFM

destination: _site

# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, .last_optimized]

gems:
  - image_optim
  - jemoji
  - jekyll-sitemap

feed:
  path: atom.xml

permalink: /blog/:year/:title

# Collections
collections:
  portfolio:
    title: Projects
    output: true
